name: k-board
services:
  mongodb:
    image: mongo:latest
    container_name: k-board-mongodb
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_USERNAME:-admin}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_PASSWORD:-password123}
    volumes:
      - mongodb_data:/data/db
    networks:
      - k-board-network

  app:
    image: tatsuyakari/k-board:latest
    container_name: k-board-app
    restart: always
    ports:
      - "${APP_PORT:-3000}:3000"
    environment:
      - MONGODB_URI=mongodb://${MONGO_USERNAME:-admin}:${MONGO_PASSWORD:-password123}@mongodb:27017/k-board?authSource=admin
      - AUTH_SECRET=${AUTH_SECRET}
      - AUTH_URL=${AUTH_URL:-http://localhost:3000}
      - AUTH_TRUST_HOST=true
    volumes:
      - ./public/uploads:/app/public/uploads
    depends_on:
      - mongodb
    networks:
      - k-board-network

volumes:
  mongodb_data:


networks:
  k-board-network:
    driver: bridge
